name: preprocessing autoflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
permissions:
  contents: write
  
jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install Dependencies
        run: |
          pip install pandas scikit-learn joblib
          
      - name: Run Preprocessing Script
        run: |
          python preprocessing/automate_bravo_alfon.py \
            --input mushrooms_raw.csv \
            --output preprocessing/mushrooms_preprocessing
            
      - name: Commit and Push Preprocessed Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add preprocessing/mushrooms_preprocessing/
          git commit -m "Auto preprocessing via GitHub Actions" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
